#!/bin/sh
which dirname >/dev/null 
# does dirname exit?
if [ $? = 0 ] ; then
  cwd=`dirname $0`
  if [ x$cwd = x. ]; then
     cwd=`pwd`
  fi
  if [ x$cwd = x/opt/bacula/bin ] ; then
     echo "bconsole not properly installed."  
     exit 1
  fi
fi
if [ x/opt/bacula/bin = x/opt/bacula/conf ]; then
   echo "bconsole not properly installed."
   exit 1
fi
if [ $# = 1 ] ; then
   echo "doing bconsole $1.conf"
   /opt/bacula/bin/bconsole -c $1.conf
else
   /opt/bacula/bin/bconsole -c /opt/bacula/conf/bconsole.conf
fi
